### ISSUE TITLE
شكرا على المشاركة

### ISSUE THREAD

**Issue by alilosoft** [ahmed0saber/my-resume#1]
انا متابعك على لينكد إن، وأشكرك على مشاركاتك المفيدة، خاصة ما يتعلق بالبحث عن العمل و السيرة الذاتية.
انا بصدد نسخ هذا المستودع و استعماله كبداية لكتابة موجز السيرة الذاتية 
شكرا جزيلا و بارك الله فيك.

**Comment by ahmed0saber** [comment]
شكرا جدا لك ، وفقك الله وأعانك.
